
title: HelperBlog
email: your_email@example.com # अपनी ईमेल से बदलें
description: A blog dedicated to providing helpful guides and tutorials.
baseurl: ""
url: "https://helperblog.github.io" # आपकी GitHub Pages URL
twitter_username: your_twitter # वैकल्पिक
github_username: your_github # वैकल्पिक

permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

env: production
theme: minima
